apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: get-cache
spec:
  params:
    - name: path
      type: string
    - name: key
      type: string
  image: cgr.dev/chainguard/curl:latest-dev
  env:
    - name: CACHE_KEY
      value: $(params.key)
    - name: CACHE_FILE_PATH
      value: $(params.path)
  workingDir: /tekton/home
  script: |
    curl "http://cache-service.tekton-pipelines.svc.cluster.local:8080/${CACHE_KEY}" > "${CACHE_FILE_PATH}"
