apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: my-taskrun-
spec:
  timeout: 10m
  taskSpec:
    steps:
      - ref:
          name: get-cache
        params:
          - name: path
            value: "output.txt"
          - name: key
            value: "cache"
      - name: write-file
        workingDir: /tekton/home
        image: cgr.dev/chainguard/busybox
        script: |
          cat output.txt
          date >> output.txt
      - ref:
          name: upload-cache
        params:
          - name: path
            value: "output.txt"
          - name: key
            value: "cache"
