apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: my-taskrun-
spec:
  timeout: 10m
  taskSpec:
    steps:
      # This works
      - image: cgr.dev/chainguard/curl:latest-dev
        workingDir: /tekton/home
        script: |
          curl "http://cache-service.tekton-pipelines.svc.cluster.local:8080/cache"
      # This doesn't?
      - ref:
          name: get-cache
        params:
          - name: path
            value: "output.txt"
          - name: key
            value: "cache"
      - name: write-file
        workingDir: /tekton/home
        image: cgr.dev/chainguard/busybox
        script: |
          cat output.txt
          date >> output.txt
      - ref:
          name: upload-cache
        params:
          - name: path
            value: "output.txt"
          - name: key
            value: "cache"
