apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: my-taskrun-
spec:
  timeout: 10m
  taskSpec:
    steps:
      - ref:
          name: get-cache
        params:
          - name: path
            value: "output.txt"
          - name: key
            value: "cache"
          #- name: digest
          #   value: 08ad3ae390a374c648964ca99b1891fd869a9434f6101b433eb15fb1fd8526f6
      - name: write-file
        workingDir: /tekton/home
        image: cgr.dev/chainguard/busybox
        script: |
          cat output.txt
          date >> output.txt
      - ref:
          name: upload-cache
        params:
          - name: path
            value: "output.txt"
          - name: key
            value: "cache"
